### ISSUE TITLE
Невозможно удалить хосты из кластера мониторинга Can't remove hosts from monitoring cluster

### ISSUE THREAD

**Issue by tfedyanin** [arenadata/adcm#905] opened 2021-06-30 17:26 UTC
Если добавить хосты в кластер и раздать на них сервисы, то в дальнейшем невозможно без удаления кластера исключить хост, так как на странице разметки сервисов невозможно сохранить если не установлен обязательный сервис Graphite.
А при попытке удаления хоста имеем
 CONFLICT ] HOST_CONFLICT -- Host #13 has component(s)

UPD.
If I add hosts to monitoring cluster and bind them with services, then I can't remove that hosts without removing cluster completely.
This happens because of mandatory Graphite service. It can't be deleted from host, and host with any binded service can't be deleted

**Comment by dgusakov** [comment] 2021-07-06 05:42
Hi, Timofey! Could you please provide versions of ADCM and all bundles used? Given description is not enough to find out if this is an issue or expected behavior.

**Comment by tfedyanin** [comment] 2021-07-06 08:07
@dgusakov , hello! 
VERSION: 2021.06.17.06-87238cbd

**Comment by dgusakov** [comment] 2021-07-22 14:19
@tfedyanin This is a version of the ADCM itself. All clusters in ADCM are created from bundles. To investigate your issue we need a version of this bundle. See screenshot below for example:
<img width="719" alt="Screenshot 2021-07-22 at 17 16 38" src="https://user-images.githubusercontent.com/40051639/126654569-2856412a-5123-480d-acee-657dba856732.png">

**Comment by VO0v** [comment] 2021-07-23 06:35
@dgusakov, hello.
Version ADB bundle: 
name	ADB
version	6.16.2_arenadata21_b1-1
edition	community

**Comment by dgusakov** [comment] 2021-07-23 07:22
I think I got you now. There is no ability to remove monitoring components from the Arenadata Monitoring cluster now. We have plans about implementing this feature but actual planned dates are not available now. Pls consider checking new arenadata_monitoring versions at https://store.arenadata.io/

Since this issue is not related to the ADCM directly I will close this issue.

**Closed by dgusakov** 2021-07-23 07:22 UTC
